config/routes.rb
Rails.application.routes.draw do
  get 'teachers/index'
  get 'students/index'
  get 'teachers/my_courses'
  get 'teachers/exam_dates'
  get 'students/my_courses'
  get 'students/exam_dates'
  devise_for :students, path: 'students'
  devise_for :teachers, path: 'teachers'
  resources :courses do
    resources :exams
    post 'upload_result'
    post 'remove_result'
  end
  
  post 'exams/upload'
  post 'exams/remove_paper'
  post 'courses/:id/enroll', to: 'courses#enroll', as: 'enroll'
  post 'courses/:id/unenroll', to: 'courses#unenroll', as: 'unenroll'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  
  get 'tilki/list_exams'
  get 'tilki/check_in'
  get 'tilki/verify_key'
  post 'tilki/upload'
  
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :courses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index

  end
  
  def my_courses
    @my_courses = Course.where(:teacher_id => current_teacher.id)
  end
  
  def exam_dates
    @cs = Course.where(:teacher_id => current_teacher.id)
    Rails.logger.debug("cs: #{@cs.inspect}")
    @exams = Exam.where(:course_id => @cs.map(&:id))
    Rails.logger.debug("exams: #{@exams.inspect}")
    @dates =  @exams.map(&:start_time).to_s
    @names =  @exams.map(&:name)
    Rails.logger.debug("dates: #{@dates.inspect}")
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_sidebar.html.erb
<nav class="navbar navbar-inverse sidebar" id="sideNavbar" role="navigation">
    <div class="container-fluid">
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
			<ul class="nav navbar-nav">
			    <li><%= link_to teachers_index_path do %>
                    Index<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span>
                <% end %></li>
			    <li><%= link_to new_course_path do %>
                    Create Course<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-plus"></span>
                <% end %></li>
                <li><%= link_to teachers_my_courses_path do %>
                    My Courses<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-book"></span>
                <% end %></li>
                <li><%= link_to teachers_exam_dates_path do %>
                    Upcoming Exam Dates<span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-calendar"></span>
                <% end %></li>
			</ul>
		</div>
	</div>
</nav>


<script>
    $('#sideNavbar').css("height", $(document).height());
</script>

app/views/teachers/exam_dates.html.erb
<% provide(:title, "My Exam Dates") %>
<%= stylesheet_link_tag "sidebar.css" %>
<%= stylesheet_link_tag "card.css" %>
<%= stylesheet_link_tag "calendar.css" %>

<body class="back-im">


<%= render 'sidebar' %>


<div class="main">
  <div class="page-header" style="margin-top: -25px;">
    <center><h1 style="color:black; font-family: Ubuntu;">My Exam Dates</h1></center>
  </div>
  
  <div class="col-md-6">
    <div id="calendar">
    </div>    
  </div>

        <div class="col-md-4" style="margin-top:10%;">
          <div class="card" style="height:150px; background-color:white;">
            <div class="card-body">
              <center><h2 class="card-text" style="margin-left:5px; margin-right:5px;">Check your exam dates easily by using calendar mode!</h2></center>
            </div>
          </div>
        </div>

</div>

</body>

<script>
  var names = <%= @names.inspect.html_safe %>;
</script>

<script>
  var dates = <%= @dates.inspect.html_safe %>;

</script>



<script>
    !function() {
      
  var today = moment();

  function Calendar(selector, events) {
    this.el = document.querySelector(selector);
    this.events = events;
    this.current = moment().date(1);
    this.draw();
    var current = document.querySelector('.today');
    if(current) {
      var self = this;
      window.setTimeout(function() {
        self.openDay(current);
      }, 500);
    }
  }

  Calendar.prototype.draw = function() {
    //Create Header
    this.drawHeader();

    //Draw Month
    this.drawMonth();

    this.drawLegend();
  }

  Calendar.prototype.drawHeader = function() {
    var self = this;
    if(!this.header) {
      //Create the header elements
      this.header = createElement('div', 'header');
      this.header.className = 'header';

      this.title = createElement('h1');

      var right = createElement('div', 'right');
      right.addEventListener('click', function() { self.nextMonth(); });

      var left = createElement('div', 'left');
      left.addEventListener('click', function() { self.prevMonth(); });

      //Append the Elements
      this.header.appendChild(this.title); 
      this.header.appendChild(right);
      this.header.appendChild(left);
      this.el.appendChild(this.header);
    }

    this.title.innerHTML = this.current.format('MMMM YYYY');
  }

  Calendar.prototype.drawMonth = function() {
    var self = this;
    
    this.events.forEach(function(ev) {
     ev.date = self.current.clone().date(Math.random() * (29 - 1) + 1);
    });
    
    
    if(this.month) {
      this.oldMonth = this.month;
      this.oldMonth.className = 'month out ' + (self.next ? 'next' : 'prev');
      this.oldMonth.addEventListener('webkitAnimationEnd', function() {
        self.oldMonth.parentNode.removeChild(self.oldMonth);
        self.month = createElement('div', 'month');
        self.backFill();
        self.currentMonth();
        self.fowardFill();
        self.el.appendChild(self.month);
        window.setTimeout(function() {
          self.month.className = 'month in ' + (self.next ? 'next' : 'prev');
        }, 16);
      });
    } else {
        this.month = createElement('div', 'month');
        this.el.appendChild(this.month);
        this.backFill();
        this.currentMonth();
        this.fowardFill();
        this.month.className = 'month new';
    }
  }

  Calendar.prototype.backFill = function() {
    var clone = this.current.clone();
    var dayOfWeek = clone.day();

    if(!dayOfWeek) { return; }

    clone.subtract('days', dayOfWeek+1);

    for(var i = dayOfWeek; i > 0 ; i--) {
      this.drawDay(clone.add('days', 1));
    }
  }

  Calendar.prototype.fowardFill = function() {
    var clone = this.current.clone().add('months', 1).subtract('days', 1);
    var dayOfWeek = clone.day();

    if(dayOfWeek === 6) { return; }

    for(var i = dayOfWeek; i < 6 ; i++) {
      this.drawDay(clone.add('days', 1));
    }
  }

  Calendar.prototype.currentMonth = function() {
    var clone = this.current.clone();

    while(clone.month() === this.current.month()) {
      this.drawDay(clone);
      clone.add('days', 1);
    }
  }

  Calendar.prototype.getWeek = function(day) {
    if(!this.week || day.day() === 0) {
      this.week = createElement('div', 'week');
      this.month.appendChild(this.week);
    }
  }

  Calendar.prototype.drawDay = function(day) {
    var self = this;
    this.getWeek(day);

    //Outer Day
    var outer = createElement('div', this.getDayClass(day));
    outer.addEventListener('click', function() {
      self.openDay(this);
    });

    //Day Name
    var name = createElement('div', 'day-name', day.format('ddd'));

    //Day Number
    var number = createElement('div', 'day-number', day.format('DD'));


    //Events
    var events = createElement('div', 'day-events');
    this.drawEvents(day, events);

    outer.appendChild(name);
    outer.appendChild(number);
    outer.appendChild(events);
    this.week.appendChild(outer);
  }

  Calendar.prototype.drawEvents = function(day, element) {
    if(day.month() === this.current.month()) {
      var todaysEvents = this.events.reduce(function(memo, ev) {
        if(ev.date.isSame(day, 'day')) {
          memo.push(ev);
        }
        return memo;
      }, []);

      todaysEvents.forEach(function(ev) {
        var evSpan = createElement('span', ev.color);
        element.appendChild(evSpan);
      });
    }
  }

  Calendar.prototype.getDayClass = function(day) {
    classes = ['day'];
    if(day.month() !== this.current.month()) {
      classes.push('other');
    } else if (today.isSame(day, 'day')) {
      classes.push('today');
    }
    return classes.join(' ');
  }

  Calendar.prototype.openDay = function(el) {
    var details, arrow;
    var dayNumber = +el.querySelectorAll('.day-number')[0].innerText || +el.querySelectorAll('.day-number')[0].textContent;
    var day = this.current.clone().date(dayNumber);

    var currentOpened = document.querySelector('.details');

    //Check to see if there is an open detais box on the current row
    if(currentOpened && currentOpened.parentNode === el.parentNode) {
      details = currentOpened;
      arrow = document.querySelector('.arrow');
    } else {
      //Close the open events on differnt week row
      //currentOpened && currentOpened.parentNode.removeChild(currentOpened);
      if(currentOpened) {
        currentOpened.addEventListener('webkitAnimationEnd', function() {
          currentOpened.parentNode.removeChild(currentOpened);
        });
        currentOpened.addEventListener('oanimationend', function() {
          currentOpened.parentNode.removeChild(currentOpened);
        });
        currentOpened.addEventListener('msAnimationEnd', function() {
          currentOpened.parentNode.removeChild(currentOpened);
        });
        currentOpened.addEventListener('animationend', function() {
          currentOpened.parentNode.removeChild(currentOpened);
        });
        currentOpened.className = 'details out';
      }

      //Create the Details Container
      details = createElement('div', 'details in');

      //Create the arrow
      var arrow = createElement('div', 'arrow');

      //Create the event wrapper

      details.appendChild(arrow);
      el.parentNode.appendChild(details);
    }

    var todaysEvents = this.events.reduce(function(memo, ev) {
      if(ev.date.isSame(day, 'day')) {
        memo.push(ev);
      }
      return memo;
    }, []);

    this.renderEvents(todaysEvents, details);

    arrow.style.left = el.offsetLeft - el.parentNode.offsetLeft + 27 + 'px';
  }

  Calendar.prototype.renderEvents = function(events, ele) {
    //Remove any events in the current details element
    var currentWrapper = ele.querySelector('.events');
    var wrapper = createElement('div', 'events in' + (currentWrapper ? ' new' : ''));

    events.forEach(function(ev) {
      var div = createElement('div', 'event');
      var square = createElement('div', 'event-category ' + ev.color);
      var span = createElement('span', '', ev.eventName);

      div.appendChild(square);
      div.appendChild(span);
      wrapper.appendChild(div);
    });

    if(!events.length) {
      var div = createElement('div', 'event empty');
      var span = createElement('span', '', 'No Events');

      div.appendChild(span);
      wrapper.appendChild(div);
    }

    if(currentWrapper) {
      currentWrapper.className = 'events out';
      currentWrapper.addEventListener('webkitAnimationEnd', function() {
        currentWrapper.parentNode.removeChild(currentWrapper);
        ele.appendChild(wrapper);
      });
      currentWrapper.addEventListener('oanimationend', function() {
        currentWrapper.parentNode.removeChild(currentWrapper);
        ele.appendChild(wrapper);
      });
      currentWrapper.addEventListener('msAnimationEnd', function() {
        currentWrapper.parentNode.removeChild(currentWrapper);
        ele.appendChild(wrapper);
      });
      currentWrapper.addEventListener('animationend', function() {
        currentWrapper.parentNode.removeChild(currentWrapper);
        ele.appendChild(wrapper);
      });
    } else {
      ele.appendChild(wrapper);
    }
  }

  Calendar.prototype.drawLegend = function() {
    var legend = createElement('div', 'legend');
    var calendars = this.events.map(function(e) {
      return e.calendar + '|' + e.color;
    }).reduce(function(memo, e) {
      if(memo.indexOf(e) === -1) {
        memo.push(e);
      }
      return memo;
    }, []).forEach(function(e) {
      var parts = e.split('|');
      var entry = createElement('span', 'entry ' +  parts[1], parts[0]);
      legend.appendChild(entry);
    });
    this.el.appendChild(legend);
  }

  Calendar.prototype.nextMonth = function() {
    this.current.add('months', 1);
    this.next = true;
    this.draw();
  }

  Calendar.prototype.prevMonth = function() {
    this.current.subtract('months', 1);
    this.next = false;
    this.draw();
  }

  window.Calendar = Calendar;

  function createElement(tagName, className, innerText) {
    var ele = document.createElement(tagName);
    if(className) {
      ele.className = className;
    }
    if(innerText) {
      ele.innderText = ele.textContent = innerText;
    }
    return ele;
  }
}();

!function() {
    

  data = [];
  for (index = 0; index < names.length; ++index) {
     data.push({eventName: names[index], calendar: 'Work', color: 'orange' });
  }



  function addDate(ev) {
    
  }

  var calendar = new Calendar('#calendar', data);

}();

</script>

app/views/teachers/index.html.erb
<%= stylesheet_link_tag "sidebar.css" %>

<%= render 'sidebar' %>

<body class="back-im">

<div class="main">
<br></br>
<div class="container">
      <!-- Heading Row -->
      <div class="row">
        <div class="col-md-8">
            <%= image_tag("examination.jpg", :alt => "logo", :class => "img-fluid rounded") %>
        </div>
        <!-- /.col-lg-8 -->
        <div class="col-md-4" style="color: rgba(0, 0, 0, .68); font-family: Ubuntu;">
          <center><h1>e-Xam Your Online Examination System</h1></center>
          <p>Hi <%= current_teacher.name%>! This is your index panel, where you can create courses, access your existing courses and see your upcoming exam dates!</p>
        </div>
        <!-- /.col-md-4 -->
      </div>
      <!-- /.row -->

      <br></br>

      <!-- Content Row -->
      <div class="row" style="color: rgba(0, 0, 0, .68); font-family: Ubuntu;">
        <div class="col-md-4">
          <div class="card" style="height:200px; background-color:white;">
            <div class="card-body">
              <center><h2 class="card-title">Create Your Own Courses!</h2></center>
              <p class="card-text" style="margin-left:5px; margin-right:5px;">You can start creating your courses with the button below! So that students can enroll to your class for upcoming exams!</p>
            </div>
            <div class="card-footer">
              <%= button_to 'Create Courses', new_course_path, method: :get, class: 'btn btn-primary btn-md' %>
            </div>
          </div>
        </div>
        <!-- /.col-md-4 -->
        <div class="col-md-4">
          <div class="card" style="height:200px; background-color:white;">
            <div class="card-body">
              <center><h2 class="card-title">List Your Courses!</h2></center>
              <p class="card-text" style="margin-left:5px; margin-right:5px;">You can list your existing courses with the button below! You can select and visit any of the course page that you're tutoring</p>
            </div>
            <div class="card-footer">
              <%= button_to 'My Courses', teachers_my_courses_path, method: :get, class: 'btn btn-primary btn-md' %>
            </div>
          </div>
        </div>
        <!-- /.col-md-4 -->
        <div class="col-md-4">
          <div class="card" style="height:200px; background-color:white;">
            <div class="card-body">
              <center><h2 class="card-title">Learn Your Exam Dates</h2></center>
              <p class="card-text" style="margin-left:5px; margin-right:5px;">You can see your upcoming exams from the calendar view with the button below! So you can prepare your exam questions before the date</p>
            </div>
            <div class="card-footer">
              <%= button_to 'My Exam Dates', teachers_exam_dates_path, method: :get, class: 'btn btn-primary btn-md' %>
            </div>
          </div>
        </div>
        <!-- /.col-md-4 -->

      </div>
      <!-- /.row -->

    </div>

</div>

</body>

app/views/teachers/my_courses.html.erb
<% provide(:title, "My Courses") %>
<%= stylesheet_link_tag "sidebar.css" %>
<%= stylesheet_link_tag "card.css" %>

<body class="back-im">
<%= render 'sidebar' %>

<div class="main" style="font-family: Ubuntu;">
   <div class="col-md-offset-3 col-md-6">
      <h2 class="page-header">My Courses</h2>
      <% @my_courses.each do |f| %>
      <br> </br>
      <div class="row">
         <div class="card">
            <h3 class="card-header"><center><%= f.name %></center></h3>
            <div class="card-block">
                <p class="card-text"> <b>Course Teacher: </b><%= current_teacher.name %> <%= current_teacher.surname %></p>
                <p class="card-text"> <b>Course Description: </b><%= f.description %></p>
                <%= button_to 'Show Course', course_path(f), method: :get, class: 'btn btn-primary' %>
            </div>
         </div>
      </div>
      <% end %>
   </div>
</div>
</body>