config/routes.rb
Rails.application.routes.draw do
  get 'teachers/index'
  get 'students/index'
  get 'teachers/my_courses'
  get 'teachers/exam_dates'
  get 'students/my_courses'
  get 'students/exam_dates'
  devise_for :students, path: 'students'
  devise_for :teachers, path: 'teachers'
  resources :courses do
    resources :exams
    post 'upload_result'
    post 'remove_result'
  end
  
  post 'exams/upload'
  post 'exams/remove_paper'
  post 'courses/:id/enroll', to: 'courses#enroll', as: 'enroll'
  post 'courses/:id/unenroll', to: 'courses#unenroll', as: 'unenroll'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  
  get 'tilki/list_exams'
  get 'tilki/check_in'
  get 'tilki/verify_key'
  post 'tilki/upload'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="navbar-header" style="font-family:Helvetica;">
        <% if current_student.present? %>
          <%= link_to students_index_path do %>
            <%= image_tag("exam.png", :alt => "logo", :class => "navbar-brand") %>
          <% end %>
        <% elsif current_teacher.present?%>
          <%= link_to teachers_index_path do %>
            <%= image_tag("exam.png", :alt => "logo", :class => "navbar-brand") %>
          <% end %>
        <% else %>
          <%= link_to root_path do %>
            <%= image_tag("exam.png", :alt => "logo", :class => "navbar-brand") %>
          <% end %>        
        <% end %>
      </div>
      <div id="navbar6" class="navbar-collapse collapse" style="font-family:Helvetica;">
        <ul class="nav navbar-nav navbar-right" style="margin-right:5px;">
          <% if current_student.present? %>
            <li><a><%= current_student.name%> <%= current_student.surname%></a></li>
            <li><%= link_to "Sign Out", destroy_student_session_path, method: :delete %></li>
          <% elsif current_teacher.present?%>
            <li><a><%= current_teacher.name%> <%= current_teacher.surname%></a></li>
            <li><%= link_to "Sign Out", destroy_teacher_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Teacher Log In", new_teacher_session_path %></li>
            <li><%= link_to "Student Log In", new_student_session_path %></li>
          <% end %>
        </ul>
      <!--/.nav-collapse -->
    </div>
    <!--/.container-fluid -->
  </nav>

  <body>
    <%= yield %>
  </body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</html>